# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven-plugins:
        patterns:
          - "*maven*plugin*"
          - "org.apache.maven*:*"
        exclude-patterns:
          - "io.quarkus*"
      quarkus:
        patterns:
          - "io.quarkus:*"
          - "io.quarkus.*:*"
          - "io.quarkiverse:*"
          - "io.quarkiverse.*:*"
    ignore:
      # We require JDK 11, so we don't need "-jdk8"
      - dependency-name: "org.bsc.maven:maven-processor-plugin"
        # Apparently patterns using wildcards are not supported here. Hopefully this will last until they drop these silly -jdk8 packages.
        versions: ["5.0-jdk8", "5.1-jdk8", "5.2-jdk8", "5.3-jdk8", "5.4-jdk8", "5.5-jdk8", "5.6-jdk8", "5.7-jdk8", "5.8-jdk8", "5.9-jdk8"]
      # Releases too often, it's annoying
      - dependency-name: "org.assertj:*"
        update-types: ["version-update:semver-patch"]

