= Quarkus Hibernate Search Extras

include::./includes/attributes.adoc[]

This set of extensions provide various extra features for the Quarkus Hibernate Search integration.

== AWS Integration

[[aws-request-signing]]
=== AWS request signing

If you need to use https://docs.aws.amazon.com/elasticsearch-service/[Amazon’s managed Elasticsearch service],
you will find it requires a proprietary authentication method involving request signing.

To enable AWS request signing, an additional extension is required:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="hibernate-search-orm-elasticsearch-aws"
----

Once the extension is there, you will need some more configuration:

* Configure the AWS region with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.region[`quarkus.hibernate-search-orm.elasticsearch.aws.region`].
* Enable request signing with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled[`quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled`].
* Optionally, configure how credentials are retrieved with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type[`quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type`].
The default gets the credentials from the application environment (AWS instance role, ...),
but several more options are available.

For example:

[source,properties]
----
quarkus.hibernate-search-orm.elasticsearch.aws.region=us-east-1
quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled=true
----

Or, if credentials are not available in the application environment (AWS instance role, ...):

[source,properties]
----
quarkus.hibernate-search-orm.elasticsearch.aws.region=us-east-1
quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled=true
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type=static
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.static-provider.access-key-id=AKIDEXAMPLE
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.static-provider.secret-access-key=wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY
----

[[aws-configuration-reference]]
=== AWS Integration Configuration Reference

include::./includes/quarkus-hibernate-search-orm-elasticsearch-aws.adoc[]